version: '3'
services:
  mongo:
    image: "gcr.io/steel-math-257901/mongo"
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=1q2w3e
    networks:
      - sms_network
  app:
    restart: "always"
    image: "gcr.io/steel-math-257901/sms"
    ports:
      - "80:80"
    environment:
      - API_PORT=80
      - MONGO_HOST=mongo
      - MONGO_DB=sms
      - MONGO_USER=root
      - MONGO_PASSWORD=1q2w3e
    depends_on:
      - mongo
    networks:
      - sms_network
networks:
  sms_network: