version: '3'
services:
  mongo:
    container_name: mongo-sms
    image: "gcr.io/steel-math-257901/mongo"
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=1q2w3e
    networks:
      - sms_network
  app:  
    container_name: sms
    restart: "always"
    image: "gcr.io/steel-math-257901/sms"
    ports:
      - "8080:8080"
    environment:
      - API_PORT=8080
      - MONGO_HOST=mongo
      - MONGO_DB=sms
      - MONGO_USER=root
      - MONGO_PASSWORD=1q2w3e
    networks:
      - sms_network
networks:
  sms_network: